#!/bin/bash -u

function show_cmd () {
    echo -n "$ "
    for (( i = 0; i < ${#1}; i++ )) ;
    do
        echo -n "${1:i:1}"
        sleep 0.5
    done
    echo ;
}

function show_ex_break () {
    tput setaf 3
    printf '%*s\n' $(tput cols) | tr ' ' "-"
    echo
    tput setaf 7 ;
}


cmd=pwd
echo Where am I? - ${cmd}
show_cmd ${cmd}
show_ex_break

cmd=ls
echo "What's here? - ${cmd}"
show_cmd ${cmd}
show_ex_break

cmd=cd
echo "Where's home? - ${cmd}"
show_cmd ${cmd}
show_ex_break

cmd="cd -"
echo "Where did I come from? - ${cmd}"
show_cmd "${cmd}"
show_ex_break


